export const FETCH_LAUNCHES_START="FETCH_LAUNCHES_START";
export const FETCH_LAUNCHES_SUCCESS="FETCH_LAUNCHES_SUCCESS";
export const FETCH_LAUNCHES_FAIL="FETCH_LAUNCHES_FAIL";
export const GET_SINGLE_LAUNCHES_START="GET_SINGLE_LAUNCHES_START";
export const GET_SINGLE_LAUNCHES_SUCCESS="GET_SINGLE_LAUNCHES_SUCCESS";
export const GET_SINGLE_LAUNCHES_FAIL="GET_SINGLE_LAUNCHES_FAIL";